config/routes.rb
Rails.application.routes.draw do
  get "health" => "rails/health#show", as: :rails_health_check

  # Welcome (main) page
  get  "welcome/index"
  root "welcome#index"

  # Disks
  post "disks/:id/update_content" => "disks#update_content", as: :update_content

  # Downloads
  get  "downloads" => "downloads#index"
  post "downloads" => "downloads#store"

  # Files
  get "files" => "file#index"

  # Jobs
  resources :jobs, only: [ :index, :show, :destroy, :update ]

  # Tools
  get "tools" => "tools#index"
  get "tools/find_duplicated_movies" => "tools#find_duplicated_movies"
  get "tools/find_duplicated_series" => "tools#find_duplicated_series"
  get "tools/stop_amule" => "tools#stop_amule"
  get "tools/start_amule" => "tools#start_amule"
  get "tools/copy_from_server_to_external" => "tools#copy_from_server_to_external"
  get "tools/copy_from_server_to_external/:id" => "tools#copy_from_server_to_external_status"

  # Resources
  resources :disks do
    resources :file_disks
  end
end

app/controllers/tools_controller.rb
class ToolsController < ApplicationController
  def index
  end

  def find_duplicated_movies
    logger.info "Finding duplicated movies"
    duplicated_movies = Rails.cache.fetch("duplicated_movies", expires_in: 10.minutes) do
      duplicated_movies = ActiveRecord::Base.connection.select_all(<<-SQL)
        SELECT d1.name AS fd1_disk_name, fd.fd1_disk_id, fd.fd1_filename, d2.name AS fd2_disk_name, fd.fd2_disk_id, fd.fd2_filename
        FROM (
          SELECT fd1.disk_id AS fd1_disk_id, fd1.filename AS fd1_filename, fd2.disk_id AS fd2_disk_id, fd2.filename AS fd2_filename
          FROM file_disks AS fd1
          INNER JOIN file_disks AS fd2 ON fd1.clean_title % fd2.clean_title AND fd1.id < fd2.id
          WHERE fd1.clean_title IS NOT NULL AND fd2.clean_title IS NOT NULL
          LIMIT 1000
        ) AS fd
        INNER JOIN disks AS d1 ON fd.fd1_disk_id = d1.id
        INNER JOIN disks AS d2 ON fd.fd2_disk_id = d2.id
      SQL
      duplicated_movies.to_a
    end

    @per_page = (params[:per_page] || 20).to_i
    @current_page = (params[:page] || 1).to_i

    @duplicates = Kaminari.paginate_array(duplicated_movies, total_count: duplicated_movies.size)
                          .page(@current_page)
                          .per(@per_page)
    logger.info "Found #{@duplicated_movies.size} duplicates"
  end

  def find_duplicated_series
    logger.info "Finding duplicated series"
    @duplicates = get_series_duplicates
    logger.info "Found #{@duplicates.size} series duplicated"
  end

  def stop_amule
    begin
      `sudo service amule-daemon stop`
      @message = :server_stopped_correctly
    rescue
      @message = :server_stopped_error
    end
  end

  def start_amule
    begin
      `sudo service amule-daemon start`
      @message = :server_started_correctly
    rescue
      @message = :server_started_error
    end
  end

  def copy_from_server_to_external
    job = MoveFromServerToExternalJob.perform_later
    logger.debug "Moving from server to external job with job info: #{job.inspect}"
    redirect_to job_path(job.job_id)
  end

  def copy_from_server_to_external_status
    job_id = params[:id]
    job_progress = Job.find(job_id)
    @progress = job_progress.progress
    logger.debug "Obtaining progress for job_id #{job_id}"
  end

  private

  def get_series_duplicates
    series_found = {}
    r = Regexp.compile("^series\/([^\/]+)\/.*$", true)
    FileDisk.find_each do |file_disk|
      m = r.match(file_disk.filename)
      if m
        serie_name = m[1]
        if ! series_found.has_key?(serie_name)
          series_found[serie_name] = {}
        end
        serie_disk_info = series_found[serie_name]
        series_found[serie_name] = { file_disk.disk_id => 1 } if ! serie_disk_info.has_key?(file_disk.disk_id)
      end
    end
    series_found.reject { |k, v| v.length == 1 }
  end
end

app/helpers/tools_helper.rb
module ToolsHelper
  TYPES=[ "B", "KB", "MB", "GB", "TB" ]
  def get_human_size(size)
    size = size.to_f
    type = 0
    while size > 1024
      size /= 1024
      type += 1
    end
    sprintf("%g%s", (size * 10).ceil.to_f / 10, TYPES[type]) # we will only allow 1 decimal
  end
end

app/views/tools/copy_from_server_to_external.html.erb
<h1><%= link_to t(:tools), tools_path %> / <%= t(:copy_from_server_to_external) %></h1>

<p>Job processed in background</p>
<p>Job id: <%= @job_id %></p>

app/views/tools/copy_from_server_to_external_status.html.erb
<h1><%= link_to t(:tools), tools_path %> / <%= t(:copy_from_server_to_external) %></h1>

<p>Progress: <%= @progress %></p>

app/views/tools/find_duplicated_movies.html.erb
<h1><%= link_to t(:tools), tools_path %> / <%= t(:find_duplicated_movies) %></h1>

<% if @duplicates.empty? %>
<p><%= t(:duplicated_movies_not_found) %></p>
<% else %>
<table cols="3">
  <tr>
    <th><%= t(:filename) %> 1</th>
    <th><%= t(:filename) %> 2</th>
  </tr>
<% @duplicates.each do |row| %>
  <tr>
    <td><%= row['fd1_filename'] %> (<%= row['fd1_disk_name'] %>)</td>
    <td><%= row['fd2_filename'] %> (<%= row['fd2_disk_name'] %>)</td>
  </tr>
<% end %>
</table>

<%= paginate @duplicates %>
<% end -%>

app/views/tools/find_duplicated_series.html.erb
<h1><%= link_to t(:tools), tools_path %> / <%= t(:find_duplicated_series) %></h1>

<% if @duplicates.empty? %>
<p><%= t(:duplicated_series_not_found) %></p>
<% else %>
<% @duplicates.each_pair do |seriename, serie_disk| %>
<table>
	<tr>
		<th><%= seriename %></th>
	</tr>
	<tr>
		<th><%= t(:disk) %></th>
	</tr>
	<% serie_disk.each_pair do |diskname,v| %>
	<tr>
		<td><%= diskname %></td>
	</tr>
	<% end %>
</table>
<% end %>
<% end %>

app/views/tools/find_series_duplicates.html.erb
<h1><%= link_to t(:tools), tools_path %> / <%= t(:find_duplicates) %></h1>

<% if @duplicates.empty? %>
<p><%= t(:duplicate_series_not_found) %></p>
<% else %>
<% @duplicates.each_pair do |seriename, serie_disk| %>
<table>
	<tr>
		<th><%= seriename %></th>
	</tr>
	<tr>
		<th><%= t(:disk) %></th>
	</tr>
	<% serie_disk.each_pair do |diskname,v| %>
	<tr>
		<td><%= diskname %></td>
	</tr>
	<% end %>
</table>
<% end %>
<% end %>

app/views/tools/index.html.erb
<h1><%= t(:tools) %></h1>
<%= link_to t(:find_duplicated_movies), tools_find_duplicated_movies_path, :class => 'button' %>
<p><%= t(:find_duplicated_movies_description) %></p>
<%= link_to t(:find_duplicated_series), tools_find_duplicated_series_path, :class => 'button' %>
<p><%= t(:find_duplicated_series_description) %></p>
<%= link_to t(:stop_amule), tools_stop_amule_path, :class => 'button' %>
<p><%= t(:stop_amule_description) %></p>
<%= link_to t(:start_amule), tools_start_amule_path, :class => 'button' %>
<p><%= t(:start_amule_description) %></p>
<%= link_to t(:copy_from_server_to_external), tools_copy_from_server_to_external_path, :class => 'button' %>
<p><%= t(:copy_from_server_to_external_description) %></p>

app/views/tools/start_amule.html.erb
<h1><%= link_to t(:tools), tools_path %> / <%= t(:start_amule) %></h1>

<p><%= t(@message)%></p>

app/views/tools/stop_amule.html.erb
<h1><%= link_to t(:tools), tools_path %> / <%= t(:stop_amule) %></h1>

<p><%= t(@message)%></p>