config/routes.rb
Rails.application.routes.draw do
  get "health" => "rails/health#show", as: :rails_health_check

  # Welcome (main) page
  get  "welcome/index"
  root "welcome#index"

  # Disks
  post "disks/:id/update_content" => "disks#update_content", as: :update_content

  # Downloads
  get  "downloads" => "downloads#index"
  post "downloads" => "downloads#store"

  # Files
  get "files" => "file#index"

  # Jobs
  resources :jobs, only: [ :index, :show, :destroy, :update ]

  # Tools
  get "tools" => "tools#index"
  get "tools/find_duplicated_movies" => "tools#find_duplicated_movies"
  get "tools/find_duplicated_series" => "tools#find_duplicated_series"
  get "tools/stop_amule" => "tools#stop_amule"
  get "tools/start_amule" => "tools#start_amule"
  get "tools/copy_from_server_to_external" => "tools#copy_from_server_to_external"
  get "tools/copy_from_server_to_external/:id" => "tools#copy_from_server_to_external_status"

  # Resources
  resources :disks do
    resources :file_disks
  end
end

app/controllers/file_controller.rb
class FileController < ApplicationController
  def index
    @downloads_last_update = Download.get_last_update()
    @downloads = Download.search(params[:search]) if @downloads_last_update
    @files = FileDisk.search(params[:search]).page params[:page]
  end
end

app/helpers/file_helper.rb
module FileHelper
end

app/views/file/index.html.erb
<h1><%= t(:files) %></h1>

<%= form_tag files_path, :method => "get", :remote => true, :data => { 'turboform' => true } do %>
<%= label_tag(:search, t(:search_file)) %>
<%= text_field_tag :search, params[:search], :autofocus => 'autofocus' %>
<%= submit_tag t(:search), :name => nil, :class => 'button' %>
<% end %>

<h2><%= t(:downloads) %></h2>
<% if @downloads_last_update && @downloads && ! @downloads.empty? %>
<p><strong><%= t(:last_update) %>:</strong> <%= l(@downloads_last_update) %></p>
<p><strong><%= t(:total_downloads) %>:</strong> <%= @downloads.count %></p>
<table>
	<tr>
		<th><%= t(:name) %></th>
		<th><%= t(:percentage) %></th>
	</tr>

	<% @downloads.each do |download| %>
	<tr>
		<td><%= download.filename %></td>
		<td><%= download.percentage %></td>
	</tr>
	<% end %>
</table>
<% else %>
<p><%= t(:downloads_search_not_found)%></p>
<% end -%>

<h2><%= t(:files) %></h2>
<% if @files.empty? %>
<p><%= t(:files_search_not_found)%></p>
<% else %>
<p><strong><%= t(:total_files) %>:</strong> <%= @files.count %></p>
<table>
	<tr>
		<th><%= t(:name) %></th>
		<th><%= t(:size_mb) %></th>
		<th><%= t(:score) %></th>
		<th><%= t(:disk) %></th>
		<th><%= t(:actions) %></th>
	</tr>
	<% @link_to_back = CGI.escape(Base64.encode64(request.fullpath)) %>
	<% @files.each do |file| %>
	<tr>
		<td><%= file.filename %></td>
		<td><%= file.size_mb %></td>
		<td><%= file.score %></td>
		<td><%= link_to file.disk.name, disk_path(file.disk), :class => 'ref' %></td>
		<td class="action"><%= link_to t(:destroy), [file.disk, file],
		data: { "turbo-method": :delete, "turbo-confirm": t(:question_sure) }, :class => 'button' %></td>

		<td class="action"><%= link_to(t(:edit), edit_disk_file_disk_path(:id => file.id, :disk_id => file.disk_id, :link_to_back => @link_to_back), :class => 'button') %></td>
	</tr>
	<% end %>
</table>

<%= paginate @files %>
<% end -%>