config/routes.rb
Rails.application.routes.draw do
  get "health" => "rails/health#show", as: :rails_health_check

  # Welcome (main) page
  get  "welcome/index"
  root "welcome#index"

  # Disks
  post "disks/:id/update_content" => "disks#update_content", as: :update_content

  # Downloads
  get  "downloads" => "downloads#index"
  post "downloads" => "downloads#store"

  # Files
  get "files" => "file#index"

  # Jobs
  resources :jobs, only: [ :index, :show, :destroy, :update ]

  # Tools
  get "tools" => "tools#index"
  get "tools/find_duplicated_movies" => "tools#find_duplicated_movies"
  get "tools/find_duplicated_series" => "tools#find_duplicated_series"
  get "tools/stop_amule" => "tools#stop_amule"
  get "tools/start_amule" => "tools#start_amule"
  get "tools/copy_from_server_to_external" => "tools#copy_from_server_to_external"
  get "tools/copy_from_server_to_external/:id" => "tools#copy_from_server_to_external_status"

  # Resources
  resources :disks do
    resources :file_disks
  end
end

app/models/disk.rb
require "yaml"

class Disk < ApplicationRecord
  enum :disk_type, {
    HD: "HD", DVD: "DVD", CD: "CD"
  }, prefix: true

  has_many :file_disks, -> { where(deleted: false) }, dependent: :delete_all
  validates :name, presence: true
  paginates_per 50
  broadcasts_refreshes
end

app/controllers/disks_controller.rb
require "digest"

class DisksController < ApplicationController
  before_action :set_disk, only: %i[ show edit update destroy update_content]
  rescue_from ActiveRecord::RecordNotFound, with: :disk_not_found

  # We need to include this helper to use it in view
  helper ToolsHelper

  def index
    @disks = Disk.order(:name).page params[:page]
  end

  def show
    @file_disks = @disk.file_disks.where(deleted: false).page params[:page]
  end

  def new
    @disk = Disk.new
  end

  def edit
  end

  def update
    logger.debug "Editing disk: #{@disk.attributes.inspect}"

    if @disk.update(disk_params)
      redirect_to @disk
    else
      render "edit"
    end
  end

  def create
    @disk = Disk.new(disk_params)

    if @disk.save
      redirect_to @disk
    else
      respond_to do |format|
        format.turbo_stream {
          @disk.errors.full_messages.each do |e|
            flash.now[:alert] = e
          end

          render turbo_stream: turbo_stream.replace("flash",
            partial: "shared/flash")
        }
      end
    end
  end

  def destroy
    @disk.destroy
    redirect_to disks_path, notice: I18n.t(:disk_deleted_properly)
  end

  def update_content
    job = UpdateDiskInformationJob.perform_later @disk.id
    logger.debug "Updating disk #{@disk.inspect}. Job info: #{job.inspect}"
    redirect_to job_path(job.job_id)
  end

  private

  def set_disk
    @disk = Disk.find(params[:id])
  end

  def disk_params
    params.require(:disk).permit(:name, :disk_type, :total_size, :free_size)
  end

  def disk_not_found
    render :notfound
  end
end

app/helpers/disks_helper.rb
module DisksHelper
  class HardDiskFilesUpdaterInfo
    def initialize(mount, disk_id)
      @mount = mount
      @disk_id = disk_id
      @files_to_add = []
      @files_to_update = []
      @ids_updated = Set.new
      @files_to_update = []
      @files_to_add = []
    end

    def get_files_to_add
      @files_to_add
    end

    def get_files_to_update
      @files_to_update
    end

    def get_files_to_remove
      @files_on_db ||= get_files_on_db
      @files_on_db.values.select { |file|
        not @ids_updated.include?(file.id)
      }
    end

    def add_file(file)
      @files_on_db ||= get_files_on_db
      raise Exception.new("File #{file} does not start by mount path #{@mount}") if !file.start_with?(@mount)

      internal_filename = file[(@mount.length+1)..-1]
      file_on_disk_db = @files_on_db[internal_filename]
      file_info = FileDisk.create_from_filename(file, internal_filename, @disk_id)
      file_on_db = FileDisk.find_using_filename_with_id(internal_filename)

      if file_on_db
        file_on_db.copy_from_created_from_filename(file_info)
        @files_on_db.delete(internal_filename)
        if file_info != file_on_disk_db
          file_on_db.append_id_to_filename
          @files_to_update << file_on_db
          @ids_updated.add(file_on_db.id)
        end
      elsif file_on_disk_db
        file_on_disk_db.copy_from_created_from_filename(file_info)
        file_on_disk_db.append_id_to_filename
        @files_on_db.delete(internal_filename)
        @files_to_update << file_on_disk_db
        @ids_updated.add(file_on_disk_db.id)
      else # not present neither on DB nor disk_DB -> it's new
        @files_to_add << file_info
      end
    end

    private

    def get_files_on_db
      files_on_db = {}
      Disk.find(@disk_id).file_disks.each do |file_disk|
        files_on_db[file_disk.filename] = file_disk
      end
      files_on_db
    end
  end

  class HardDiskInfo
    DEFAULT_FILE_NAME = "info"
    def self.read_from_mounted_disk(mount)
      self.read_from_yaml(File.join(mount, DEFAULT_FILE_NAME))
    end

    def self.read_from_yaml(filename)
      raise IOError.new("File <#{filename}> not found") if not File.exist?(filename)

      begin
        disk_info = YAML.load_file filename
      rescue Psych::SyntaxError
        return self.read_from_old_file(filename)
      end

      HardDiskInfo.new(disk_info["id"], disk_info["name"], filename)
    end

    def self.read_from_old_file(filename)
      raise IOError.new("File <#{filename}> not found") if not File.exist?(filename)
      content = File.open(filename).read
      content.gsub!(/\r\n?/, "\n")
      content_lines = content.lines

      line1_match = /ID Disco:\s*(\d+)/.match(content_lines[0])
      raise SyntaxError.new("Incorrect info file format") if not line1_match

      HardDiskInfo.new(line1_match[1].to_i, content_lines[1].strip(), filename)
    end

    attr_reader :id, :name, :total_size, :free_size

    def initialize(id, name, filesystem_path)
      @id = id
      @name = name

      # Obtain disk space
      stat_info = Sys::Filesystem.stat(filesystem_path)
      @total_size = stat_info.block_size * stat_info.blocks
      @free_size = stat_info.block_size * stat_info.blocks_free
    end

    def store_on_mounted_disk(mount)
      store_as_yaml(File.join(mount, DEFAULT_FILE_NAME))
    end

    def store_as_yaml(filename)
      File.open(filename, "w") do |file|
        file.write({ "id" => @id, "name" => @name }.to_yaml)
      end
    end

    def ensure_exists
      other_disk = Disk.find(@id)
      raise Exception.new(I18n.t(:update_error_disk_not_in_db)) if name != other_disk.name
    end
  end
end

app/views/disks/_form.html.erb
<%= form_for @disk do |f| %>

<p>
	<%= f.label :name %>
	<br>
	<%= f.text_field :name %>
</p>

<p>
	<%= f.label :type %>
	<br>
	<%= f.select(:disk_type) do %>
		<% Disk.disk_types.keys.each do |d| -%>
			<%= content_tag(:option, d, value: d, selected: @disk.disk_type == d) %>
		<% end %>
	<% end %>
</p>

<p>
	<%= f.label :last_update %>
	<br>
	<% if @disk.last_sync %>
		<%= l(@disk.last_sync) %>
	<% else %>
		<%= t(:last_update_not_set) %>
	<% end -%>
</p>

<p>
  <%= f.label :total_size %>
  <br>
  <%= f.text_field :total_size %>
</p>

<p>
  <%= f.label :free_size %>
  <br>
  <%= f.text_field :free_size %>
</p>

<p>
	<%= f.submit :class => 'button' %>
</p>

<% end %>

app/views/disks/edit.html.erb
<h1><%= link_to t(:disks), disks_path %> / <%= link_to @disk.name, disk_path(@disk) %> / <%= t(:edit) %></h1>

<%= render 'form' %>

app/views/disks/index.html.erb
<h1><%= t(:disks) %></h1>

<%= link_to t(:new_disk), new_disk_path, :class => 'button' %>

<%= turbo_stream_from 'disks' %>

<table>
	<tr>
		<th><%= t(:name) %></th>
		<th><%= t(:type) %></th>
		<th><%= t(:last_update) %></th>
		<th><%= t(:total_size) %></th>
		<th><%= t(:free_size) %></th>
		<th><%= t(:number_files) %></th>
		<th colspan="4"><%= t(:actions) %></th>
	</tr>

	<% @disks.each do |disk| %>
	<%= turbo_stream_from disk %>
	<tr>
		<td><%= disk.name %></td>
		<td><%= disk.disk_type %></td>
		<td><% if disk.last_sync %><%= l(disk.last_sync, format: :simple) %><% end %></td>
		<td><%= get_human_size(disk.total_size) %></td>
		<td><%= get_human_size(disk.free_size) %></td>
		<td><%= disk.file_disks.count %></td>
		<td class="action"><%= link_to t(:show), disk_path(disk), :class => 'button' %></td>
		<td class="action"><%= link_to t(:update_content), update_content_path(disk), data: { "turbo-method": :post}, :class => 'button' %></td>
		<td class="action"><%= link_to t(:edit), edit_disk_path(disk), :class => 'button' %></td>
		<td class="action"><%= link_to t(:destroy), disk_path(disk),
		data: { "turbo-method": :delete, "turbo-confirm": t(:question_sure) }, :class => 'button' %></td>
	</tr>
	<% end %>
</table>


<%= paginate @disks %>

app/views/disks/new.html.erb
<h1><%= link_to t(:disks), disks_path %> / <%= t(:new_disk) %></h1>

<%= render 'form' %>

app/views/disks/notfound.html.erb
<h1><%= link_to t(:disks), disks_path %> / <%= t(:not_found) %></h1>

app/views/disks/show.html.erb
<h1><%= link_to t(:disks), disks_path %> / <%= @disk.name %></h1>

<%= link_to 'Edit', edit_disk_path(@disk), :class => 'button' %>

<%= turbo_stream_from @disk %>

<p>
	<strong><%= t(:name) %>:</strong>
	<%= @disk.name %>
</p>

<p>
	<strong><%= t(:type) %>:</strong>
	<%= @disk.disk_type %>
</p>

<p>
	<strong><%= t(:last_update) %>:</strong>
	<% if @disk.last_sync %>
		<%= l(@disk.last_sync) %>
	<% else %>
		<%= t(:last_update_not_set) %>
	<% end -%>
</p>

<p>
  <strong><%= t(:total_size) %>:</strong>
  <%= get_human_size(@disk.total_size) %>
</p>

<p>
  <strong><%= t(:free_size) %>:</strong>
  <%= get_human_size(@disk.free_size) %>
</p>

<h2><%= t(:files) %></h2>
<table>
	<tr>
		<th><%= t(:filename) %></th>
		<th><%= t(:size_mb) %></th>
		<th><%= t(:score) %></th>
		<th colspan="2"><%= t(:actions) %></th>
	</tr>
	<% @link_to_back = CGI.escape(Base64.encode64(request.path)) %>
	<%= render @file_disks %>
</table>
<%= paginate @file_disks %>