config/routes.rb
Rails.application.routes.draw do
  get "health" => "rails/health#show", as: :rails_health_check

  # Welcome (main) page
  get  "welcome/index"
  root "welcome#index"

  # Disks
  post "disks/:id/update_content" => "disks#update_content", as: :update_content

  # Downloads
  get  "downloads" => "downloads#index"
  post "downloads" => "downloads#store"

  # Files
  get "files" => "file#index"

  # Jobs
  resources :jobs, only: [ :index, :show, :destroy, :update ]

  # Tools
  get "tools" => "tools#index"
  get "tools/find_duplicated_movies" => "tools#find_duplicated_movies"
  get "tools/find_duplicated_series" => "tools#find_duplicated_series"
  get "tools/stop_amule" => "tools#stop_amule"
  get "tools/start_amule" => "tools#start_amule"
  get "tools/copy_from_server_to_external" => "tools#copy_from_server_to_external"
  get "tools/copy_from_server_to_external/:id" => "tools#copy_from_server_to_external_status"

  # Resources
  resources :disks do
    resources :file_disks
  end
end

app/models/job.rb
class JobError < Exception
end

class JobCancellingAlreadyFinishedError < JobError
end

class JobDeletingUnfinishedError < JobError
end

class Job < ApplicationRecord
  enum :finish_status, {
    UNFINISHED: "UNFINISHED", FINISHED_WITH_ERRORS: "FINISHED_WITH_ERRORS",
    FINISHED_CORRECTLY: "FINISHED_CORRECTLY", CANCELLED: "CANCELLED"
  }, prefix: true

  paginates_per 50
  broadcasts_refreshes
  before_destroy :check_finished

  def upgrade_progress(progress, progress_stage = nil)
    self.progress = progress
    self.progress_stage = progress_stage if progress_stage
    self.save
  end

  def cancel
    raise JobCancellingAlreadyFinishedError.new if self.finish_status != "UNFINISHED"
    self.progress = self.progress_max
    self.finish_status = :CANCELLED
    self.progress_stage = I18n.t(:update_content_cancelled)
    self.save
  end

  def finish_correctly
    self.progress = self.progress_max
    self.finish_status = :FINISHED_CORRECTLY
    self.save
  end

  def finish_with_errors(error_message)
    self.finish_status = :FINISHED_WITH_ERRORS
    self.error_message = error_message
    self.save
  end

  def is_cancelled?
    self.reload
    self.finish_status == :CANCELLED
  end

  def self.where_unfinished_or_finished_in_seven_days
    self.where("finish_status = ?", :UNFINISHED).or(
      self.where("finish_status <> ?", :UNFINISHED).and(
        self.where("DATE(updated_at) >= ?", Date.today - 1.week)
      )
    )
  end

  def check_finished
    if self.finish_status == :UNFINISHED
      raise JobDeletingUnfinishedError.new
    end
  end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :set_job, only: %i[ show update destroy ]
  rescue_from ActiveRecord::RecordNotFound, with: :job_not_found

  def index
    @jobs = Job.where_unfinished_or_finished_in_seven_days.order("created_at DESC").page params[:page]
  end

  def show
  end

  def destroy
    begin
      @job.destroy
      redirect_to jobs_path, notice: I18n.t(:job_deleted_properly)
    rescue JobError => e
      message = case e
      when JobDeletingUnfinishedError
        I18n.t(:job_destroy_error_only_finished)
      else
        I18n.t(:unknown_error)
      end

      respond_to do |format|
        format.turbo_stream {
          flash.now[:alert] = message
          render turbo_stream: turbo_stream.replace("flash",
            partial: "shared/flash")
        }
      end
    end
  end

  def update
    if params[:task] == "cancel"
      logger.info "Cancelling job with ID: #{@job.id}"
      begin
        @job.cancel
        redirect_to jobs_path, notice: I18n.t(:job_canceled_properly)
      rescue JobError => e
        message = case e
        when JobCancellingAlreadyFinishedError
          I18n.t(:job_cancel_error_only_unfished)
        else
          I18n.t(:unknown_error)
        end

        respond_to do |format|
          format.turbo_stream {
            flash.now[:alert] = message
            render turbo_stream: turbo_stream.replace("flash",
              partial: "shared/flash")
          }
        end
      end
    end
  end

  private

  def set_job
    @job = Job.find(params[:id])
  end

  def job_not_found
    render :notfound
  end
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/jobs/index.html.erb
<h1><%= t(:jobs) %></h1>

<%= turbo_stream_from 'jobs' %>

<table>
  <tr>
    <th><%= t(:name) %></th>
    <th><%= t(:stage) %></th>
    <th><%= t(:error) %></th>
    <th><%= t(:progress) %></th>
    <th><%= t(:creation) %></th>
    <th><%= t(:last_update) %></th>
    <th colspan="3"><%= t(:actions) %></th>
  </tr>
  <% @jobs.each do |job| %>
  <%= turbo_stream_from job %>
	<tr>
		<td><%= job.description %></td>
    <td><%= job.progress_stage %></td>
    <td><%= job.error_message %></td>
    <td><%= job.progress %>/<%= job.progress_max %></td>
    <td><%= job.created_at %></td>
    <td><%= job.updated_at %></td>
    <td class="action"><%= link_to t(:show), job_path(job), :class => 'button' %></td>
    <td class="action"><%= link_to t(:cancel), job_path(job, :task => 'cancel' ),
    data: { "turbo-method": :put, "turbo-confirm": t(:question_sure) }, :class => 'button' %></td>
    <td class="action"><%= link_to t(:destroy), job_path(job),
		data: { "turbo-method": :delete, "turbo-confirm": t(:question_sure) }, :class => 'button' %></td>
	</tr>
	<% end %>
</table>
<%= paginate @jobs %>

app/views/jobs/notfound.html.erb
<h1><%= link_to t(:jobs), jobs_path %> / <%= t(:not_found) %></h1>

app/views/jobs/show.html.erb
<h1><%= @job.id %></h1>

<%= turbo_stream_from @job %>

<p>
	<strong><%= t(:name) %>:</strong>
	<%= @job.description %>
</p>
<p>
	<strong><%= t(:stage) %>:</strong>
	<span id="progresstext"><%= @job.progress_stage %></span>
</p>

<% if @job.finish_status_FINISHED_WITH_ERRORS? %>
<p>
  <strong><%= t(:error) %>:</strong>
  <%= @job.error_message %>
</p>
<% end %>

<p>
	<strong><%= t(:progress) %>:</strong>
	<span id="progressnumber"><%= @job.progress %></span>% <progress id="progressbar" value="<%= @job.progress %>" max="100"></progress>
</p>

<p>
	<strong><%= t(:creation) %>:</strong>
	<%= @job.created_at %>
</p>
<p>
	<strong><%= t(:last_update) %>:</strong>
	<%= @job.updated_at %>
</p>